/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import java.io.IOException;


public class App {


    public static void main(String[] args) throws IOException {
getAndSaveQuoteLocally first_quote=new getAndSaveQuoteLocally("https://favqs.com/api/qotd");
System.out.println(first_quote);
    }


}
